# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/bigattichouse/workspace/headlessweb/.venv/lib/python3.12/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/bigattichouse/workspace/headlessweb/.venv/lib/python3.12/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bigattichouse/workspace/headlessweb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bigattichouse/workspace/headlessweb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	.venv/lib/python3.12/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	.venv/lib/python3.12/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bigattichouse/workspace/headlessweb/CMakeFiles /home/bigattichouse/workspace/headlessweb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bigattichouse/workspace/headlessweb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hweb-poc

# Build rule for target.
hweb-poc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hweb-poc
.PHONY : hweb-poc

# fast build rule for target.
hweb-poc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/build
.PHONY : hweb-poc/fast

src/Browser/Browser.o: src/Browser/Browser.cpp.o
.PHONY : src/Browser/Browser.o

# target to build an object file
src/Browser/Browser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Browser.cpp.o
.PHONY : src/Browser/Browser.cpp.o

src/Browser/Browser.i: src/Browser/Browser.cpp.i
.PHONY : src/Browser/Browser.i

# target to preprocess a source file
src/Browser/Browser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Browser.cpp.i
.PHONY : src/Browser/Browser.cpp.i

src/Browser/Browser.s: src/Browser/Browser.cpp.s
.PHONY : src/Browser/Browser.s

# target to generate assembly for a file
src/Browser/Browser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Browser.cpp.s
.PHONY : src/Browser/Browser.cpp.s

src/Browser/Core.o: src/Browser/Core.cpp.o
.PHONY : src/Browser/Core.o

# target to build an object file
src/Browser/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Core.cpp.o
.PHONY : src/Browser/Core.cpp.o

src/Browser/Core.i: src/Browser/Core.cpp.i
.PHONY : src/Browser/Core.i

# target to preprocess a source file
src/Browser/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Core.cpp.i
.PHONY : src/Browser/Core.cpp.i

src/Browser/Core.s: src/Browser/Core.cpp.s
.PHONY : src/Browser/Core.s

# target to generate assembly for a file
src/Browser/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Core.cpp.s
.PHONY : src/Browser/Core.cpp.s

src/Browser/DOM.o: src/Browser/DOM.cpp.o
.PHONY : src/Browser/DOM.o

# target to build an object file
src/Browser/DOM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/DOM.cpp.o
.PHONY : src/Browser/DOM.cpp.o

src/Browser/DOM.i: src/Browser/DOM.cpp.i
.PHONY : src/Browser/DOM.i

# target to preprocess a source file
src/Browser/DOM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/DOM.cpp.i
.PHONY : src/Browser/DOM.cpp.i

src/Browser/DOM.s: src/Browser/DOM.cpp.s
.PHONY : src/Browser/DOM.s

# target to generate assembly for a file
src/Browser/DOM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/DOM.cpp.s
.PHONY : src/Browser/DOM.cpp.s

src/Browser/Events.o: src/Browser/Events.cpp.o
.PHONY : src/Browser/Events.o

# target to build an object file
src/Browser/Events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Events.cpp.o
.PHONY : src/Browser/Events.cpp.o

src/Browser/Events.i: src/Browser/Events.cpp.i
.PHONY : src/Browser/Events.i

# target to preprocess a source file
src/Browser/Events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Events.cpp.i
.PHONY : src/Browser/Events.cpp.i

src/Browser/Events.s: src/Browser/Events.cpp.s
.PHONY : src/Browser/Events.s

# target to generate assembly for a file
src/Browser/Events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Events.cpp.s
.PHONY : src/Browser/Events.cpp.s

src/Browser/JavaScript.o: src/Browser/JavaScript.cpp.o
.PHONY : src/Browser/JavaScript.o

# target to build an object file
src/Browser/JavaScript.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/JavaScript.cpp.o
.PHONY : src/Browser/JavaScript.cpp.o

src/Browser/JavaScript.i: src/Browser/JavaScript.cpp.i
.PHONY : src/Browser/JavaScript.i

# target to preprocess a source file
src/Browser/JavaScript.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/JavaScript.cpp.i
.PHONY : src/Browser/JavaScript.cpp.i

src/Browser/JavaScript.s: src/Browser/JavaScript.cpp.s
.PHONY : src/Browser/JavaScript.s

# target to generate assembly for a file
src/Browser/JavaScript.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/JavaScript.cpp.s
.PHONY : src/Browser/JavaScript.cpp.s

src/Browser/Screenshot.o: src/Browser/Screenshot.cpp.o
.PHONY : src/Browser/Screenshot.o

# target to build an object file
src/Browser/Screenshot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Screenshot.cpp.o
.PHONY : src/Browser/Screenshot.cpp.o

src/Browser/Screenshot.i: src/Browser/Screenshot.cpp.i
.PHONY : src/Browser/Screenshot.i

# target to preprocess a source file
src/Browser/Screenshot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Screenshot.cpp.i
.PHONY : src/Browser/Screenshot.cpp.i

src/Browser/Screenshot.s: src/Browser/Screenshot.cpp.s
.PHONY : src/Browser/Screenshot.s

# target to generate assembly for a file
src/Browser/Screenshot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Screenshot.cpp.s
.PHONY : src/Browser/Screenshot.cpp.s

src/Browser/Session.o: src/Browser/Session.cpp.o
.PHONY : src/Browser/Session.o

# target to build an object file
src/Browser/Session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Session.cpp.o
.PHONY : src/Browser/Session.cpp.o

src/Browser/Session.i: src/Browser/Session.cpp.i
.PHONY : src/Browser/Session.i

# target to preprocess a source file
src/Browser/Session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Session.cpp.i
.PHONY : src/Browser/Session.cpp.i

src/Browser/Session.s: src/Browser/Session.cpp.s
.PHONY : src/Browser/Session.s

# target to generate assembly for a file
src/Browser/Session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Session.cpp.s
.PHONY : src/Browser/Session.cpp.s

src/Browser/Storage.o: src/Browser/Storage.cpp.o
.PHONY : src/Browser/Storage.o

# target to build an object file
src/Browser/Storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Storage.cpp.o
.PHONY : src/Browser/Storage.cpp.o

src/Browser/Storage.i: src/Browser/Storage.cpp.i
.PHONY : src/Browser/Storage.i

# target to preprocess a source file
src/Browser/Storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Storage.cpp.i
.PHONY : src/Browser/Storage.cpp.i

src/Browser/Storage.s: src/Browser/Storage.cpp.s
.PHONY : src/Browser/Storage.s

# target to generate assembly for a file
src/Browser/Storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Storage.cpp.s
.PHONY : src/Browser/Storage.cpp.s

src/Browser/Utilities.o: src/Browser/Utilities.cpp.o
.PHONY : src/Browser/Utilities.o

# target to build an object file
src/Browser/Utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Utilities.cpp.o
.PHONY : src/Browser/Utilities.cpp.o

src/Browser/Utilities.i: src/Browser/Utilities.cpp.i
.PHONY : src/Browser/Utilities.i

# target to preprocess a source file
src/Browser/Utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Utilities.cpp.i
.PHONY : src/Browser/Utilities.cpp.i

src/Browser/Utilities.s: src/Browser/Utilities.cpp.s
.PHONY : src/Browser/Utilities.s

# target to generate assembly for a file
src/Browser/Utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Browser/Utilities.cpp.s
.PHONY : src/Browser/Utilities.cpp.s

src/Session/Manager.o: src/Session/Manager.cpp.o
.PHONY : src/Session/Manager.o

# target to build an object file
src/Session/Manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Session/Manager.cpp.o
.PHONY : src/Session/Manager.cpp.o

src/Session/Manager.i: src/Session/Manager.cpp.i
.PHONY : src/Session/Manager.i

# target to preprocess a source file
src/Session/Manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Session/Manager.cpp.i
.PHONY : src/Session/Manager.cpp.i

src/Session/Manager.s: src/Session/Manager.cpp.s
.PHONY : src/Session/Manager.s

# target to generate assembly for a file
src/Session/Manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Session/Manager.cpp.s
.PHONY : src/Session/Manager.cpp.s

src/Session/Session.o: src/Session/Session.cpp.o
.PHONY : src/Session/Session.o

# target to build an object file
src/Session/Session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Session/Session.cpp.o
.PHONY : src/Session/Session.cpp.o

src/Session/Session.i: src/Session/Session.cpp.i
.PHONY : src/Session/Session.i

# target to preprocess a source file
src/Session/Session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Session/Session.cpp.i
.PHONY : src/Session/Session.cpp.i

src/Session/Session.s: src/Session/Session.cpp.s
.PHONY : src/Session/Session.s

# target to generate assembly for a file
src/Session/Session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/Session/Session.cpp.s
.PHONY : src/Session/Session.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hweb-poc.dir/build.make CMakeFiles/hweb-poc.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hweb-poc"
	@echo "... src/Browser/Browser.o"
	@echo "... src/Browser/Browser.i"
	@echo "... src/Browser/Browser.s"
	@echo "... src/Browser/Core.o"
	@echo "... src/Browser/Core.i"
	@echo "... src/Browser/Core.s"
	@echo "... src/Browser/DOM.o"
	@echo "... src/Browser/DOM.i"
	@echo "... src/Browser/DOM.s"
	@echo "... src/Browser/Events.o"
	@echo "... src/Browser/Events.i"
	@echo "... src/Browser/Events.s"
	@echo "... src/Browser/JavaScript.o"
	@echo "... src/Browser/JavaScript.i"
	@echo "... src/Browser/JavaScript.s"
	@echo "... src/Browser/Screenshot.o"
	@echo "... src/Browser/Screenshot.i"
	@echo "... src/Browser/Screenshot.s"
	@echo "... src/Browser/Session.o"
	@echo "... src/Browser/Session.i"
	@echo "... src/Browser/Session.s"
	@echo "... src/Browser/Storage.o"
	@echo "... src/Browser/Storage.i"
	@echo "... src/Browser/Storage.s"
	@echo "... src/Browser/Utilities.o"
	@echo "... src/Browser/Utilities.i"
	@echo "... src/Browser/Utilities.s"
	@echo "... src/Session/Manager.o"
	@echo "... src/Session/Manager.i"
	@echo "... src/Session/Manager.s"
	@echo "... src/Session/Session.o"
	@echo "... src/Session/Session.i"
	@echo "... src/Session/Session.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

